version: '3'

services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang
    container_name: goapp
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - goapp
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email sammy@example.com --agree-tos --no-eff-email --force-renewal -d sammidev.codes  -d www.sammidev.codes 

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/sammidev/go-greet/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge